var dato = new Date();
dato.
var source = {'realtorId': 0, 'prodId': 0, 'responsibleRealtor': 'test', 'type': 0, 'price': 1337, 'zipcode': 1337, 'zipArea': 'baerum',  'location': 'trondheim', 'headLine': 'line', 'adress':'adress 37'}

$.ajax({type: "POST", dataType: "json", url: "/api/MasterAPI", data: JSON.stringify({model:source})});

var source = {'':{'RealtorId': 0, 'ProductId': 0, 'ResponsibleRealtor': 'test', 'Type': 0, 'Price': 1337, 'ZipCode': 1337, 'ZipArea': 'baerum',  'Location': 'trondheim', 'HeadLine': 'line', 'Adress':'adress 37'}}


var source = {'':{RealtorId: 0, ProductId: 0, ResponsibleRealtor: 'test', Type: 0, Price: 1337, ZipCode: 1337, ZipArea: 'baerum',  Location: 'trondheim', HeadLine: 'line', Adress:'adress 37'}}
$.ajax({type: "POST", dataType: "json", url: "/api/MasterAPI", data: JSON.stringify({model:source})});


RealEstateAdInfo.realtorId=0&RealEstateAdInfo.prodId=0&RealEstateAdInfo.responsibleRealtor=test&RealEstateAdInfo.type=0&RealEstateAdInfo.price=1337&RealEstateAdInfo.zipcode=1337&RealEstateAdInfo.zipArea=baerum&RealEstateAdInfo.location=trondheim&RealEstateAdInfo.headLine=line&RealEstateAdInfo.adress=adress37

var source = {  "RealtorId": 1,  "ProductId": 2,  "ResponsibleRealtor": "sample string 3",  "Area": "sample string 4",  "Type": 5,  "Price": 6,  "Location": "sample string 7",  "Headline": "sample string 8",  "Adress": "sample string 9",  "ZipCode": 10,  "ZipArea": "sample string 11",  "BookingDate": "2013-11-16T13:59:06.2943257+01:00",  "FinnCode": 1,  "ContractNr": 1,  "PRom": 1.1,  "Boa": 1.1,  "Bta": 1.1,  "Bra": 1.1,  "Costs": 1,  "PurchaseCosts": 1,  "CommonCosts": 1,  "AmountSharedDebt": 1,  "CommonExpenses": 1,  "PropertyArea": 1,  "PropertyType": 1,  "ConstructionYear": "2013-11-16T13:59:06.2973259+01:00",  "Floor": 1,  "Bedrooms": 1,  "Rooms": 1,  "OpenHouseDate": "2013-11-16T13:59:06.298326+01:00",  "OpenHouseText": "sample string 13",  "RealEstAgentName": "sample string 14",  "RealEstAgentTitle": "sample string 15",  "RealEstAgentMobile": 1,  "RealEstAgentPhone": 1,  "RealEstAgentEmail": "sample string 16",  "AdText": "sample string 17"}
var source = {  "<RealtorId>k__BackingField": 1,  "<ProductId>k__BackingField": 2,  "<ResponsibleRealtor>k__BackingField": "sample string 3",  "<Area>k__BackingField": "sample string 4",  "<Type>k__BackingField": 5,  "<Price>k__BackingField": 6,  "<Location>k__BackingField": "sample string 7",  "<Headline>k__BackingField": "sample string 8",  "<Adress>k__BackingField": "sample string 9",  "<ZipCode>k__BackingField": 10,  "<ZipArea>k__BackingField": "sample string 11",  "<BookingDate>k__BackingField": "2013-11-16T15:25:41.8884722+01:00",  "<FinnCode>k__BackingField": 1,  "<ContractNr>k__BackingField": 1,  "<PRom>k__BackingField": 1.1,  "<Boa>k__BackingField": 1.1,  "<Bta>k__BackingField": 1.1,  "<Bra>k__BackingField": 1.1,  "<Costs>k__BackingField": 1,  "<PurchaseCosts>k__BackingField": 1,  "<CommonCosts>k__BackingField": 1,  "<AmountSharedDebt>k__BackingField": 1,  "<CommonExpenses>k__BackingField": 1,  "<PropertyArea>k__BackingField": 1,  "<PropertyType>k__BackingField": 1,  "<ConstructionYear>k__BackingField": "2013-11-16T15:25:41.8914724+01:00",  "<Floor>k__BackingField": 1,  "<Bedrooms>k__BackingField": 1,  "<Rooms>k__BackingField": 1,  "<OpenHouseDate>k__BackingField": "2013-11-16T15:25:41.8914724+01:00",  "<OpenHouseText>k__BackingField": "sample string 13",  "<RealEstAgentName>k__BackingField": "sample string 14",  "<RealEstAgentTitle>k__BackingField": "sample string 15",  "<RealEstAgentMobile>k__BackingField": 1,  "<RealEstAgentPhone>k__BackingField": 1,  "<RealEstAgentEmail>k__BackingField": "sample string 16",  "<AdText>k__BackingField": "sample string 17"}
$.ajax({type: "POST", dataType: "json", url: "/api/UploadAPI", data: JSON.stringify({model:source})});