//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annonse
    {
        public long AnnonseID { get; set; }
        public byte PartnerID { get; set; }
        public Nullable<byte> BrukerID { get; set; }
        public Nullable<System.DateTime> DatoReg { get; set; }
        public Nullable<byte> InndelingID { get; set; }
        public string Beskrivelse { get; set; }
        public string Kommentar { get; set; }
        public Nullable<byte> ModulID { get; set; }
    }
}
