//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brukerlogg
    {
        public long ID { get; set; }
        public System.DateTime DateReg { get; set; }
        public string BrukerID { get; set; }
        public string Passord { get; set; }
        public string HTTP_REFERER { get; set; }
        public string HTTP_USER_AGENT { get; set; }
        public string REMOTE_HOST { get; set; }
        public string Program { get; set; }
    }
}
