//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ekstrasider
    {
        public byte Ukenr { get; set; }
        public short År { get; set; }
        public byte PartnerID { get; set; }
        public short Type { get; set; }
        public Nullable<int> Antall { get; set; }
    }
}
