//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fotograf
    {
        public int FotografID { get; set; }
        public byte RolleID { get; set; }
        public byte LeverandorID { get; set; }
        public string Fornavn { get; set; }
        public string Etternavn { get; set; }
        public string Initialer { get; set; }
        public string Tittel { get; set; }
        public string Epost { get; set; }
        public string Passord { get; set; }
        public string Telefon { get; set; }
        public string Mobil { get; set; }
        public Nullable<byte> Sortering { get; set; }
        public Nullable<bool> Aktiv { get; set; }
    }
}
