//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gjestebok
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Dato { get; set; }
        public string Navn { get; set; }
        public string Epost { get; set; }
        public string Melding { get; set; }
        public Nullable<bool> Aktiv { get; set; }
    }
}
