//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inndeling
    {
        public byte InndelingID { get; set; }
        public string Inndelingnavn { get; set; }
        public string AnnonseInndelingnavn { get; set; }
    }
}
