//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class langBoligtype
    {
        public byte BoligtypeID { get; set; }
        public string Boligtypenavn { get; set; }
        public Nullable<byte> BoligtypeSokID { get; set; }
        public Nullable<int> Sortering { get; set; }
        public Nullable<int> SorteringListe { get; set; }
        public string LangID { get; set; }
    }
}
