//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFoto
    {
        public long FotoID { get; set; }
        public long FotooppdragID { get; set; }
        public string Bildenavn { get; set; }
        public string Bildetekst { get; set; }
        public string Bildetype { get; set; }
        public Nullable<byte> Sortering { get; set; }
        public Nullable<bool> AktivLeveranse { get; set; }
        public Nullable<bool> AktivImport { get; set; }
        public System.DateTime DatoReg { get; set; }
    }
}
