//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwListe_ProduktModuler
    {
        public string Expr2 { get; set; }
        public string Expr1 { get; set; }
        public int Expr3 { get; set; }
        public string Modulfilnavn { get; set; }
        public string Modulnavn { get; set; }
        public string Modulkode { get; set; }
        public string Mål { get; set; }
        public byte Antallbilder { get; set; }
    }
}
