//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnonseModul
    {
        public byte ModulID { get; set; }
        public byte ProduktID { get; set; }
        public string Modulnavn { get; set; }
        public string Modulkode { get; set; }
        public decimal Modulstørrelse { get; set; }
        public string Mål { get; set; }
    }
}
