//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoligtypeSok
    {
        public byte BoligtypeSokID { get; set; }
        public string BoligtypeSoknavn { get; set; }
        public byte Sortering { get; set; }
    }
}
