//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmaBruker
    {
        public FirmaBruker()
        {
            this.FirmaBrukerHarProduktOppdaters = new HashSet<FirmaBrukerHarProduktOppdater>();
            this.Produkts = new HashSet<Produkt>();
        }
    
        public int FirmaBrukerID { get; set; }
        public int FirmaID { get; set; }
        public string Brukernavn { get; set; }
        public string Passord { get; set; }
        public string Fornavn { get; set; }
        public string Etternavn { get; set; }
        public string Epost { get; set; }
        public string Telefon { get; set; }
        public string Mobil { get; set; }
        public Nullable<bool> Aktiv { get; set; }
    
        public virtual Firma Firma { get; set; }
        public virtual ICollection<FirmaBrukerHarProduktOppdater> FirmaBrukerHarProduktOppdaters { get; set; }
        public virtual ICollection<Produkt> Produkts { get; set; }
    }
}
