//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fotooppdrag
    {
        public long FotooppdragID { get; set; }
        public System.DateTime DatoReg { get; set; }
        public byte PartnerID { get; set; }
        public int BrukerID { get; set; }
        public int FotografID { get; set; }
        public byte FotoStatusID { get; set; }
        public byte FotoTypeID { get; set; }
        public byte OppdragTypeID { get; set; }
        public Nullable<byte> OppdragTypeID2 { get; set; }
        public byte FotoSoneID { get; set; }
        public string Oppdragsnr { get; set; }
        public string Adresse { get; set; }
        public string Postnr { get; set; }
        public string Poststed { get; set; }
        public string Kontaktperson { get; set; }
        public string KontaktpersonEpost { get; set; }
        public string TelefonPrivat { get; set; }
        public string TelefonMobil { get; set; }
        public string TelefonArbeid { get; set; }
        public Nullable<bool> KontaktMegler { get; set; }
        public Nullable<bool> Panorama { get; set; }
        public Nullable<bool> Styling { get; set; }
        public Nullable<bool> StylingOK { get; set; }
        public string TilleggsInformasjon { get; set; }
        public string Kommentar { get; set; }
        public Nullable<System.DateTime> DatoBooking { get; set; }
        public Nullable<byte> FakturaOK { get; set; }
        public Nullable<bool> BildepakkeLevert { get; set; }
        public string MeldingEpost { get; set; }
        public string MeldingSMS { get; set; }
        public Nullable<System.DateTime> DatoLeveranse { get; set; }
        public Nullable<System.DateTime> DatoLeveranse360 { get; set; }
    
        public virtual FotoOppdragType FotoOppdragType { get; set; }
        public virtual FotoSone FotoSone { get; set; }
        public virtual FotoStatu FotoStatu { get; set; }
        public virtual FotoType FotoType { get; set; }
    }
}
