//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.Avdelings = new HashSet<Avdeling>();
            this.Brukers = new HashSet<Bruker>();
            this.PartnerHarProdukts = new HashSet<PartnerHarProdukt>();
            this.ProduktHarModuls = new HashSet<ProduktHarModul>();
            this.XmlRules = new HashSet<XmlRule>();
        }
    
        public byte PartnerID { get; set; }
        public string Partnernavn { get; set; }
        public string Kortnavn { get; set; }
        public Nullable<byte> StedID { get; set; }
        public string Katalog { get; set; }
        public string KundeID { get; set; }
        public Nullable<bool> PDFGodkjenning { get; set; }
        public string OrdrenrSuffix { get; set; }
        public string EpostKundeansvarlig { get; set; }
        public string Logonavn { get; set; }
        public string Logo { get; set; }
        public string PanoramaIkon { get; set; }
        public Nullable<byte> MeglersystemID { get; set; }
        public string MeglersystemBrukernavn { get; set; }
        public string MeglersystemPassord { get; set; }
        public Nullable<bool> Bildepakke { get; set; }
        public Nullable<bool> Bildevedlegg { get; set; }
        public Nullable<bool> Bilderedusert { get; set; }
        public string FinnPartnerID { get; set; }
        public Nullable<bool> FotoKunde { get; set; }
        public Nullable<bool> UseEditor { get; set; }
        public bool UseTextEdit { get; set; }
        public string MeglersystemKontorID { get; set; }
    
        public virtual ICollection<Avdeling> Avdelings { get; set; }
        public virtual ICollection<Bruker> Brukers { get; set; }
        public virtual ICollection<PartnerHarProdukt> PartnerHarProdukts { get; set; }
        public virtual ICollection<ProduktHarModul> ProduktHarModuls { get; set; }
        public virtual ICollection<XmlRule> XmlRules { get; set; }
    }
}
