//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        public Produkt()
        {
            this.FirmaHarProdukts = new HashSet<FirmaHarProdukt>();
            this.ModulStandards = new HashSet<ModulStandard>();
            this.PartnerHarProdukts = new HashSet<PartnerHarProdukt>();
            this.ProduktHarAnnonses = new HashSet<ProduktHarAnnonse>();
            this.ProduktHarModuls = new HashSet<ProduktHarModul>();
            this.ProspektHarBestillings = new HashSet<ProspektHarBestilling>();
            this.FirmaBrukers = new HashSet<FirmaBruker>();
            this.InHouse_Bruker = new HashSet<InHouse_Bruker>();
        }
    
        public byte ProduktID { get; set; }
        public string Produktnavn { get; set; }
        public string ProduktnavnAdmin { get; set; }
        public string Kommentar { get; set; }
        public string DagerUtgivelse { get; set; }
        public byte ModulerPrSide { get; set; }
        public bool Aktiv { get; set; }
        public bool AktivInDesign { get; set; }
        public bool Paraplyannonse { get; set; }
        public Nullable<byte> ModulStr { get; set; }
        public string ALDAanntype { get; set; }
        public Nullable<short> LåsStart { get; set; }
        public Nullable<short> LåsSlutt { get; set; }
        public Nullable<short> BookingFristStart { get; set; }
        public Nullable<short> BookingFristSlutt { get; set; }
        public string EpostKundeansvarlig { get; set; }
        public string ImageActionSet { get; set; }
        public Nullable<int> PrintDPI { get; set; }
        public Nullable<bool> AktivSideombrekking { get; set; }
    
        public virtual ICollection<FirmaHarProdukt> FirmaHarProdukts { get; set; }
        public virtual ICollection<ModulStandard> ModulStandards { get; set; }
        public virtual ICollection<PartnerHarProdukt> PartnerHarProdukts { get; set; }
        public virtual ICollection<ProduktHarAnnonse> ProduktHarAnnonses { get; set; }
        public virtual ICollection<ProduktHarModul> ProduktHarModuls { get; set; }
        public virtual ICollection<ProspektHarBestilling> ProspektHarBestillings { get; set; }
        public virtual ICollection<FirmaBruker> FirmaBrukers { get; set; }
        public virtual ICollection<InHouse_Bruker> InHouse_Bruker { get; set; }
    }
}
