//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspektHarBestilling
    {
        public long ProspektID { get; set; }
        public System.DateTime DatoBest { get; set; }
        public byte ProduktID { get; set; }
        public string Ordrenr { get; set; }
        public Nullable<byte> Ordrestatus { get; set; }
        public int ModulID { get; set; }
        public string Filnavn { get; set; }
        public string FilnavnProd { get; set; }
        public Nullable<bool> Nyhet { get; set; }
        public Nullable<byte> Prisfaktor { get; set; }
        public Nullable<System.DateTime> DatoReg { get; set; }
        public Nullable<System.DateTime> DatoEndret { get; set; }
        public Nullable<System.DateTime> DatoGenPdf { get; set; }
        public Nullable<bool> ErGodkjentAvMegler { get; set; }
        public Nullable<bool> GenTilProd { get; set; }
        public Nullable<bool> PaaminnelseSendt { get; set; }
        public Nullable<int> GodkjentAvBrukerID { get; set; }
        public Nullable<bool> PDFEksportert { get; set; }
        public string Dokument { get; set; }
    
        public virtual Bruker Bruker { get; set; }
        public virtual Produkt Produkt { get; set; }
    }
}
