//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspektHarUtgivelse
    {
        public long ProspektID { get; set; }
        public byte Ukenr { get; set; }
        public short År { get; set; }
        public string Ordrenr { get; set; }
        public Nullable<byte> Ordrestatus { get; set; }
    }
}
