//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistikk
    {
        public decimal StatID { get; set; }
        public string BrukerID { get; set; }
        public Nullable<System.DateTime> RegDato { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<long> ProspektID { get; set; }
        public string Program { get; set; }
    }
}
