//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statkart
    {
        public long ID { get; set; }
        public System.DateTime DatoReg { get; set; }
        public string Recordtype { get; set; }
        public Nullable<byte> Nummer { get; set; }
        public Nullable<short> Postnr { get; set; }
        public string Adressetype { get; set; }
        public Nullable<short> Kommunenr { get; set; }
        public Nullable<int> Gatekode { get; set; }
        public Nullable<short> Husnummer { get; set; }
        public string Bokstav { get; set; }
        public Nullable<short> Undernummer { get; set; }
        public Nullable<short> KommunenrEiendom { get; set; }
        public Nullable<short> Gaardsnummer { get; set; }
        public Nullable<short> Bruksnummer { get; set; }
        public Nullable<short> Festenummer { get; set; }
        public Nullable<short> Seksjonsnummer { get; set; }
        public Nullable<short> Tinglysingsembetenummer { get; set; }
        public Nullable<short> Dagbokaar { get; set; }
        public Nullable<int> Dagboknummer { get; set; }
        public Nullable<System.DateTime> Dagbokdato { get; set; }
        public Nullable<byte> Omsetningstype { get; set; }
        public string AnvendelseGrunn { get; set; }
        public string BoligtypeMed { get; set; }
        public string Utlyst { get; set; }
        public Nullable<long> Engangsbelop { get; set; }
        public string Beskrivelse { get; set; }
        public string Adresse { get; set; }
        public string Selger { get; set; }
        public string Kjoper { get; set; }
    }
}
