//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatiskTekst
    {
        public long StatiskTekstID { get; set; }
        public string LangID { get; set; }
        public string Tekst { get; set; }
    
        public virtual Lang Lang { get; set; }
    }
}
