//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tilleggstjeneste
    {
        public int TjenesteTypeID { get; set; }
        public string TjenesteTypenavn { get; set; }
        public string TjenesteTypenavnFork { get; set; }
        public Nullable<int> Pris { get; set; }
    }
}
