//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwNotarFoto2
    {
        public Nullable<System.DateTime> DatoBooking { get; set; }
        public string Adresse { get; set; }
        public string FotoSonenavn { get; set; }
        public string FotoSonenavnFork { get; set; }
        public Nullable<byte> FakturaOK { get; set; }
        public long FotooppdragID { get; set; }
        public string Etternavn { get; set; }
    }
}
