//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProspekterHarBestilling
    {
        public long ProspektID { get; set; }
        public System.DateTime DatoBest { get; set; }
        public byte ProduktID { get; set; }
        public string Produktnavn { get; set; }
        public string BBVisning { get; set; }
    }
}
