//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webassistenten_ads
{
    using System;
    using System.Collections.Generic;
    
    public partial class XmlTag
    {
        public XmlTag()
        {
            this.XmlRules = new HashSet<XmlRule>();
            this.Moduls = new HashSet<Modul>();
        }
    
        public string Tag { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<XmlRule> XmlRules { get; set; }
        public virtual ICollection<Modul> Moduls { get; set; }
    }
}
